version: '3.8'

services:
  db:
    image: postgres
    container_name: pgtest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flaskweb
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASS: pass123